In [1]:
import pooled_ppi as pp

In [2]:
pp.string_db.read_table(data_id='protein.links').head(3)

     protein1      protein2  combined_score
0  4932.Q0010  4932.YMR207C             333
1  4932.Q0010  4932.YCR051W             205
2  4932.Q0010  4932.YPR002W             195

In [3]:
pp.string_db.read_table(data_id='protein.links.detailed').head(3)

,protein1,protein2,neighborhood,fusion,cooccurence,coexpression,experimental,database,textmining,combined_score
0,4932.Q0010,4932.YMR207C,45,0,0,95,0,245,99,333
1,4932.Q0010,4932.YCR051W,0,0,0,0,180,0,71,205
2,4932.Q0010,4932.YPR002W,0,0,0,52,116,0,117,195

In [4]:
pp.string_db.read_table(data_id='protein.info').head(3)

,string_protein_id,preferred_name,protein_size,annotation
0,4932.Q0010,Q0010,128,"Putative uncharacterized protein Q0010, mitoch..."
1,4932.Q0017,Q0017,53,"Putative uncharacterized protein Q0017, mitoch..."
2,4932.Q0032,Q0032,96,"Putative uncharacterized protein Q0032, mitoch..."